version: '3.8'

networks:
  skeletonbr:
    driver: bridge

services:
  db:
    container_name: db
    image: postgres:15.1-alpine
    networks:
      - skeletonbr
    restart: always
    working_dir: /app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 15432:5432
    volumes:
      - ./db/dump:/app/dump
      - ./db/postgresql:/var/lib/postgresql/data

  php-fpm:
    container_name: php-skeleton
    networks:
      - skeletonbr
    build:
      context: ./docker/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    working_dir: /var/www
#    extra_hosts:
#      - host.docker.internal:host-getaway

  nginx:
    container_name: nginx
    networks:
      - skeletonbr
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
volumes:
  posgresql: